// Minimal player metadata for client-side pool counting in Settings
// Full player objects are sent from the server when the game starts
export const ALL_PLAYERS_META = [
  { nationality: 'Brazil', league: 'Premier League' },
  { nationality: 'Netherlands', league: 'Premier League' },
  { nationality: 'England', league: 'Premier League' },
  { nationality: 'Egypt', league: 'Premier League' },
  { nationality: 'Uruguay', league: 'Premier League' },
  { nationality: 'Colombia', league: 'Premier League' },
  { nationality: 'Hungary', league: 'Premier League' },
  { nationality: 'Argentina', league: 'Premier League' },
  { nationality: 'Spain', league: 'Premier League' },
  { nationality: 'France', league: 'Premier League' },
  { nationality: 'Norway', league: 'Premier League' },
  { nationality: 'England', league: 'Premier League' },
  { nationality: 'England', league: 'Premier League' },
  { nationality: 'Brazil', league: 'Premier League' },
  { nationality: 'Germany', league: 'Premier League' },
  { nationality: 'Belgium', league: 'Premier League' },
  { nationality: 'Brazil', league: 'Premier League' },
  { nationality: 'Portugal', league: 'Premier League' },
  { nationality: 'Belgium', league: 'Premier League' },
  { nationality: 'Norway', league: 'Premier League' },
  { nationality: 'England', league: 'Premier League' },
  { nationality: 'Portugal', league: 'Premier League' },
  { nationality: 'Spain', league: 'Premier League' },
  { nationality: 'Cameroon', league: 'Premier League' },
  { nationality: 'Portugal', league: 'Premier League' },
  { nationality: 'Brazil', league: 'Premier League' },
  { nationality: 'England', league: 'Premier League' },
  { nationality: 'England', league: 'Premier League' },
  { nationality: 'England', league: 'Premier League' },
  { nationality: 'Argentina', league: 'Premier League' },
  { nationality: 'Senegal', league: 'Premier League' },
  { nationality: 'South Korea', league: 'Premier League' },
  { nationality: 'England', league: 'Premier League' },
  { nationality: 'Brazil', league: 'Premier League' },
  { nationality: 'Sweden', league: 'Premier League' },
  { nationality: 'Brazil', league: 'Premier League' },
  { nationality: 'England', league: 'Premier League' },
  { nationality: 'Argentina', league: 'Premier League' },
  { nationality: 'England', league: 'Premier League' },
  { nationality: 'Jamaica', league: 'Premier League' },
  { nationality: 'Belgium', league: 'La Liga' },
  { nationality: 'Spain', league: 'La Liga' },
  { nationality: 'Brazil', league: 'La Liga' },
  { nationality: 'Germany', league: 'La Liga' },
  { nationality: 'Uruguay', league: 'La Liga' },
  { nationality: 'England', league: 'La Liga' },
  { nationality: 'Croatia', league: 'La Liga' },
  { nationality: 'Germany', league: 'La Liga' },
  { nationality: 'Brazil', league: 'La Liga' },
  { nationality: 'Brazil', league: 'La Liga' },
  { nationality: 'France', league: 'La Liga' },
  { nationality: 'France', league: 'La Liga' },
  { nationality: 'France', league: 'La Liga' },
  { nationality: 'Germany', league: 'La Liga' },
  { nationality: 'Spain', league: 'La Liga' },
  { nationality: 'France', league: 'La Liga' },
  { nationality: 'Spain', league: 'La Liga' },
  { nationality: 'Spain', league: 'La Liga' },
  { nationality: 'Spain', league: 'La Liga' },
  { nationality: 'Brazil', league: 'La Liga' },
  { nationality: 'Poland', league: 'La Liga' },
  { nationality: 'Spain', league: 'La Liga' },
  { nationality: 'Spain', league: 'La Liga' },
  { nationality: 'Slovenia', league: 'La Liga' },
  { nationality: 'France', league: 'La Liga' },
  { nationality: 'Argentina', league: 'La Liga' },
  { nationality: 'Argentina', league: 'La Liga' },
  { nationality: 'England', league: 'La Liga' },
  { nationality: 'Spain', league: 'La Liga' },
  { nationality: 'Spain', league: 'La Liga' },
  { nationality: 'Spain', league: 'La Liga' },
  { nationality: 'Germany', league: 'Bundesliga' },
  { nationality: 'Canada', league: 'Bundesliga' },
  { nationality: 'France', league: 'Bundesliga' },
  { nationality: 'Germany', league: 'Bundesliga' },
  { nationality: 'Germany', league: 'Bundesliga' },
  { nationality: 'Germany', league: 'Bundesliga' },
  { nationality: 'England', league: 'Bundesliga' },
  { nationality: 'Germany', league: 'Bundesliga' },
  { nationality: 'France', league: 'Bundesliga' },
  { nationality: 'South Korea', league: 'Bundesliga' },
  { nationality: 'Switzerland', league: 'Bundesliga' },
  { nationality: 'Germany', league: 'Bundesliga' },
  { nationality: 'Germany', league: 'Bundesliga' },
  { nationality: 'Germany', league: 'Bundesliga' },
  { nationality: 'Germany', league: 'Bundesliga' },
  { nationality: 'Switzerland', league: 'Bundesliga' },
  { nationality: 'Germany', league: 'Bundesliga' },
  { nationality: 'Nigeria', league: 'Bundesliga' },
  { nationality: 'Germany', league: 'Bundesliga' },
  { nationality: 'Netherlands', league: 'Bundesliga' },
  { nationality: 'Belgium', league: 'Bundesliga' },
  { nationality: 'Portugal', league: 'Bundesliga' },
  { nationality: 'Switzerland', league: 'Serie A' },
  { nationality: 'Italy', league: 'Serie A' },
  { nationality: 'Netherlands', league: 'Serie A' },
  { nationality: 'Italy', league: 'Serie A' },
  { nationality: 'Turkey', league: 'Serie A' },
  { nationality: 'France', league: 'Serie A' },
  { nationality: 'Argentina', league: 'Serie A' },
  { nationality: 'Serbia', league: 'Serie A' },
  { nationality: 'Turkey', league: 'Serie A' },
  { nationality: 'Italy', league: 'Serie A' },
  { nationality: 'France', league: 'Serie A' },
  { nationality: 'France', league: 'Serie A' },
  { nationality: 'Portugal', league: 'Serie A' },
  { nationality: 'United States', league: 'Serie A' },
  { nationality: 'Netherlands', league: 'Serie A' },
  { nationality: 'Italy', league: 'Serie A' },
  { nationality: 'Italy', league: 'Serie A' },
  { nationality: 'Slovakia', league: 'Serie A' },
  { nationality: 'Belgium', league: 'Serie A' },
  { nationality: 'Italy', league: 'Serie A' },
  { nationality: 'Nigeria', league: 'Serie A' },
  { nationality: 'Netherlands', league: 'Serie A' },
  { nationality: 'Italy', league: 'Serie A' },
  { nationality: 'Italy', league: 'Serie A' },
  { nationality: 'Italy', league: 'Ligue 1' },
  { nationality: 'Brazil', league: 'Ligue 1' },
  { nationality: 'Morocco', league: 'Ligue 1' },
  { nationality: 'France', league: 'Ligue 1' },
  { nationality: 'Spain', league: 'Ligue 1' },
  { nationality: 'Portugal', league: 'Ligue 1' },
  { nationality: 'France', league: 'Ligue 1' },
  { nationality: 'Georgia', league: 'Ligue 1' },
  { nationality: 'France', league: 'Ligue 1' },
  { nationality: 'Portugal', league: 'Ligue 1' },
  { nationality: 'Russia', league: 'Ligue 1' },
  { nationality: 'Switzerland', league: 'Ligue 1' },
  { nationality: 'Gabon', league: 'Ligue 1' },
  { nationality: 'France', league: 'Ligue 1' },
  { nationality: 'France', league: 'Ligue 1' },
  { nationality: 'Nigeria', league: 'Ligue 1' },
  { nationality: 'France', league: 'Ligue 1' },
  { nationality: 'Canada', league: 'Ligue 1' },
  { nationality: 'Argentina', league: 'Other' },
  { nationality: 'Portugal', league: 'Other' },
  { nationality: 'Brazil', league: 'Other' },
  { nationality: 'Argentina', league: 'Serie A' },
  { nationality: 'Italy', league: 'Serie A' },
  { nationality: 'Italy', league: 'Other' },
  { nationality: 'Italy', league: 'Other' },
  { nationality: 'Germany', league: 'La Liga' },
  { nationality: 'Ivory Coast', league: 'Other' },
  { nationality: 'Netherlands', league: 'Other' },
  { nationality: 'Netherlands', league: 'La Liga' },
  { nationality: 'Netherlands', league: 'Premier League' },
  { nationality: 'Ghana', league: 'Premier League' },
  { nationality: 'Belgium', league: 'Premier League' },
  { nationality: 'Germany', league: 'Bundesliga' },
  { nationality: 'France', league: 'Bundesliga' },
  { nationality: 'Iceland', league: 'Serie A' },
  { nationality: 'Ukraine', league: 'Serie A' },
  { nationality: 'Tunisia', league: 'Other' },
];
